add "ignore" function to set key's status to "ignore" in jobs table
datajoint/datajoint-python pull request #1068
Opened 2023-01-09 21:52 UTC by ttngu207

Add method to the "Jobs" class to set a job `key` to "ignore" status (similar to the existing methods of "reserve" and "error")

2023-02-12 06:19 UTC, guzman-raphael requested changes
@ttngu207 Thanks for this contribution! :clap: 

Feature looks great. Minor suggestion about documentation but otherwise this is ready.

2023-02-12 06:19 UTC, guzman-raphael commented on datajoint/jobs.py
> +        :return: True if ignore job successfully. False = the jobs is already taken
Would you update this to a [Google Style](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) docstring? That is what we are supposed to be using for API docs w/ MkDocs Material.

2023-02-13 14:53 UTC, dimitri-yatsenko reviewed
Looks good. Just add entry in CHANGELOG

2023-02-13 15:36 UTC, guzman-raphael approved these changes

2023-02-13 15:36 UTC, merged