Cascade restriction attribute
datajoint/datajoint-python pull request #1160
Opened 2024-06-11 21:27 UTC by CBroz1

2024-07-15 18:22 UTC, dimitri-yatsenko requested changes
This is a really good catch.  Thank you.

2024-07-15 18:22 UTC, dimitri-yatsenko commented on CHANGELOG.md
> +- Fixed - `cascade` passes `_restriction_attributes` when passing `_restriction` - PR [#1160](https://github.com/datajoint/datajoint-python/pull/1060)
```suggestion
- Fixed - Issue [#1159]((https://github.com/datajoint/datajoint-python/pull/1059)  (cascading delete)  - PR [#1160](https://github.com/datajoint/datajoint-python/pull/1060)

2024-07-15 18:47 UTC, dimitri-yatsenko approved these changes

2024-07-15 18:48 UTC, merged

2024-08-13 16:16 UTC, ethho commented
> Pytests show unrelated errors related to an SSL certificate

`docker pull datajoint/nginx:latest` before running tests should fix this. CI always pulls latest image, which is why this doesn't appear in GHA runs.