Fix bug with unions.
datajoint/datajoint-python pull request #964
Opened 2021-09-20 21:35 UTC by jverswijver

Added handling for when union gets a union object inside its make_sql(), this allows you to do multiple unions.
Took the test from @guzman-raphael comments on the issue linked.

fix #926

2021-09-20 21:51 UTC, jverswijver commented
Seems the test coverage api we use is experiencing a major outage, tests all pass locally. We can run the github actions when they are back up [(outage information)](https://status.coveralls.io/).

2021-09-20 22:24 UTC, dimitri-yatsenko approved these changes

2021-09-24 22:05 UTC, guzman-raphael requested changes
@jverswijver Nice work on this one man! :rocket:
Only small suggestions included but overall fix looks great.

2021-09-24 22:05 UTC, guzman-raphael commented on datajoint/expression.py
> +            return "({sql1}) UNION ({sql2})".format(sql1=sql1, sql2=sql2)
Nice catch! :clap: 

Here is a small suggestion that is mindful of code coverage by use of ternary operators.

```suggestion
            return "({sql1}) UNION ({sql2})".format(
                sql1=arg1.make_sql() if isinstance(arg1, Union) else arg1.make_sql(fields),
                sql2=arg2.make_sql() if isinstance(arg2, Union) else arg2.make_sql(fields),
                )
```

2021-10-01 18:30 UTC, guzman-raphael requested changes

2021-10-01 18:30 UTC, guzman-raphael commented on tests/test_relational_operand.py
> +        assert_set_equal(x, y)
@jverswijver Just tagged up on this point and looks like this test should have passed. Must still be something missing with this fix. Let me know once you've pinpointed the problem/solution. Thanks :handshake:

2022-02-09 16:55 UTC, A-Baji commented
It seems mysql [does not support nested unions](https://bugs.mysql.com/bug.php?id=3347) in 5.7. In 8.0 the issue is semi fixed where it allows left side nested unions, but throws a specific error for unsupported right side nested unions. However, there is a workaround where wrapping the query and all sub queries in a `SELECT * FROM ()` and then adding alias allows the query to execute properly.

2022-02-09 17:25 UTC, dimitri-yatsenko commented on datajoint/expression.py
> +        return '' if not self.restriction else ' WHERE (%s)' % ')AND('.join(
we don't really need the extra space but no big deal

2022-02-09 17:59 UTC, guzman-raphael approved these changes
@jverswijver @A-Baji :rocket: Excellent job guys and great collab! :rocket: 

It is too bad that MySQL has such nuances in working with unions but glad we were able to workaround them to achieve full union nesting support.

2022-02-09 18:00 UTC, merged

2024-11-12 04:17 UTC, renniek commented
Hi there, 

I am using datajoint version 0.13.7, and so I think this should be fixed based on what I've seen online for the different versions, but I am still getting this error when I try to do a union on more than 2 tables. Any advice? Thank you so much!